### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Taccio33** [TheUnderTaker11/More-Avaritia#12] opened 2018-11-18 18:04 UTC
Crush 
[crash-2018-11-18_18.45.22-client.txt](https://github.com/TheUnderTaker11/More-Avaritia/files/2593069/crash-2018-11-18_18.45.22-client.txt)

**Comment by walker-dev** [comment] 2018-11-18 21:41
dupe of #11

**Closed as completed** 2018-11-23 12:07 UTC
